#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# $HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:42:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              off        \
                window_opacity             off           \
                window_opacity_duration    0.1         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.90         \
                window_border              on           \
                window_border_width        1            \
                window_border_hidpi        off          \
                window_border_radius       12           \
                window_animation_duration  0.22         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                0           \
                bottom_padding             6           \
                left_padding               6           \
                right_padding              6           \
                window_gap                 6

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Messages|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Activity Monitor|MongoDB Compass|Discord)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."

# export external_bar_height="0"
# export external_bar_position="top"
# export shadow_toggle="off"
# export mouse_mod="ctrl"
# export border_toggle="on"
# export border_width="2"
# export border_radius="0"
# export opacity_toggle="off"
# export layout="bsp"
# export gap_width="12"
# export animation_duration="0"
# export autoraise_toggle="on"

# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# if [[ $autoraise_toggle == "on" ]]; then
#    yabai -m config focus_follows_mouse autoraise
# fi

# yabai -m config window_shadow $shadow_toggle
# yabai -m config mouse_modifier $mouse_mod
# yabai -m config layout $layout
# yabai -m config window_animation_duration $animation_duration
# yabai -m config window_border_radius $border_radius

# yabai -m config window_opacity             $opacity_toggle
# yabai -m config window_opacity_duration    0.2
# yabai -m config active_window_opacity      1.0
# yabai -m config normal_window_opacity      0.9

# ### Confgure mouse usage ###
# yabai -m config mouse_action1              move   # with left click - resize
# yabai -m config mouse_action2              resize     # with right click - move

# yabai -m config window_border $border_toggle
# yabai -m config window_border_width $border_width
# yabai -m config active_window_border_color 0xFF6faec0
# yabai -m config normal_window_border_color 0xFF3e4050

# if [[ $external_bar_position == "top" ]]; then
#    yabai -m config top_padding                44
#    yabai -m config bottom_padding             8
#    yabai -m config left_padding               8
#    yabai -m config right_padding              8
#    yabai -m config window_gap                 8

# fi
# if [[ $external_bar_position == "bottom" ]]; then
#    yabai -m config top_padding                $gap_width
#    yabai -m config bottom_padding             $(expr $gap_width + $external_bar_height)
#    yabai -m config left_padding               $gap_width
#    yabai -m config right_padding              $gap_width
#    yabai -m config window_gap                 $gap_width

# fi
# if [[ $external_bar_position == "left" ]]; then
#    yabai -m config top_padding                $gap_width
#    yabai -m config bottom_padding             $gap_width
#    yabai -m config left_padding               $(expr $gap_width + $external_bar_height)
#    yabai -m config right_padding              $gap_width
#    yabai -m config window_gap                 $gap_width

# fi
# if [[ $external_bar_position == "right" ]]; then
#    yabai -m config top_padding                $gap_width
#    yabai -m config bottom_padding             $gap_width
#    yabai -m config left_padding              $gap_width
#    yabai -m config right_padding              $(expr $gap_width + $external_bar_height)
#    yabai -m config window_gap                 $gap_width

# fi

# yabai -m rule --add app="^(Calculator|System Settings|ColorSlurp|zoom.us|Photo Booth|Archive Utility|Color Picker|balenaEtcher)$" manage=off
# yabai -m rule --add app="^(XQuartz)$" layer=above manage=off

# yabai -m space 1 --label Code
# yabai -m space 2 --label Text
# yabai -m space 3 --label Web
# yabai -m space 4 --label Idle
# yabai -m space 5 --label Misc
# yabai -m space 6 --label doc
# yabai -m space 7 --label help
# yabai -m space 8 --label music

# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change"

# echo "yabai configuration loaded.."
