#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    hardcoded_dirs="~/dotfiles"
    search_dirs="$(find ~/code ~/frvr -mindepth 1 -maxdepth 1 -type d | sed "s|${HOME}|~|")"
    selected=$(echo -e "$hardcoded_dirs\n$search_dirs" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
selected_dir=$(echo $selected | sed "s|~|${HOME}|")
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected_dir
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected_dir
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi

